template = ""
rev_id = 9
template_sha = "40afa223ab00844a035cff537a1d85d88c975bf8"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "vot"
__UND2C_TRG__ = "ru"
__UNDEFINED_SOURCE__ = "Votic"
__UNDEFINED_TARGET__ = "Russian"
__UND_SRC__ = "vot"
__UND_TRG__ = "rus"
