template = ""
rev_id = 5
template_sha = "b1bcc12f5675c5b86f53da0a290c53417f28d6e3"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "vot"
__UND2C_TRG__ = "ru"
__UNDEFINED_SOURCE__ = "Votic"
__UNDEFINED_TARGET__ = "Russian"
__UND_SRC__ = "vot"
__UND_TRG__ = "rus"
